//==================todo==================
export const ADD_TODO = "ADD_TODO";
export const ADD_TODO_PENDING = "ADD_TODO_PENDING";
export const ADD_TODO_FULFILLED = "ADD_TODO_FULFILLED";
export const ADD_TODO_REJECTED = "ADD_TODO_REJECTED";

export const DROP_TODO = "DROP_TODO";
export const DROP_TODO_PENDING = "DROP_TODO_PENDING";
export const DROP_TODO_FULFILLED = "DROP_TODO_FULFILLED";
export const DROP_TODO_REJECTED = "DROP_TODO_REJECTED";

export const TOGGLE_FAVORITE = "TOGGLE_FAVORITE";
export const TOGGLE_FAVORITE_PENDING = "TOGGLE_FAVORITE_PENDING";
export const TOGGLE_FAVORITE_FULFILLED = "TOGGLE_FAVORITE_FULFILLED";
export const TOGGLE_FAVORITE_REJECTED = "TOGGLE_FAVORITE_REJECTED";
